# Generated by Django 4.0.2 on 2022-02-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Imtahanin vaxti')),
                ('required_score', models.IntegerField(help_text='Kecme bali')),
            ],
        ),
    ]
